CREATE TABLE IF NOT EXISTS row_data
(
    company                       TEXT,
    wallet_bank                   TEXT,
    transaction_date              TIMESTAMP,
    depositdate                   TIMESTAMP,
    withdrawaldate                TIMESTAMP,
    norm_date                     TIMESTAMP,
    pay_id                        TEXT,
    status                        TEXT,
    amount                        NUMERIC,
    currency                      TEXT,
    commission                    NUMERIC,
    commissioncurrency            TEXT,
    exchangerate                  NUMERIC,
    finalamount                   NUMERIC,
    project                       TEXT,
    notes                         TEXT,
    reference                     TEXT,
    paymentmethod                 TEXT,
    settlement                    NUMERIC,
    settlementcomission           NUMERIC,
    topups                        NUMERIC,
    topupscomission               NUMERIC,
    affilates                     NUMERIC,
    affilatescommission           NUMERIC,
    chargebacksrefunds            NUMERIC,
    chargebacksrefundscommission  NUMERIC,
    expenses                      NUMERIC,
    expensescommission            NUMERIC,
    notes222                      TEXT,
    notes333                      TEXT,
    notes444                      TEXT,
    source_path                   TEXT,
    relative_source_path          TEXT,
    source_file                   TEXT,
    source_row_number             BIGINT,
    source_sheet_name             TEXT,
    folder_1                      TEXT,
    folder_2                      TEXT,
    folder_3                      TEXT,
    folder_4                      TEXT,
    folder_5                      TEXT,
    ingestion_id                  UUID PRIMARY KEY,
    ingestion_time                TIMESTAMPTZ,
    raw_hash                      CHAR(64),
    normalization_time            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    normalization_error           TEXT,
    raw_data                      JSONB
);