CREATE TABLE normalized_data
(
    company                         TEXT,
    wallet_bank                     TEXT,
    "date"                          TIMESTAMP,
    depositdate                     TIMESTAMP,
    withdrawaldate                  TIMESTAMP,
    norm_date                       TIMESTAMP,
    pay_id                          TEXT,
    status                          TEXT,
    amount                          NUMERIC(18,4),
    currency                        TEXT,
    commission                      NUMERIC(18,4),
    commissioncurrency              TEXT,
    exchangerate                    NUMERIC(18,8),
    finalamount                     NUMERIC(18,4),
    project                         TEXT,
    notes                           TEXT,
    reference                       TEXT,
    paymentmethod                   TEXT,
    settlement                      NUMERIC(18,4),
    settlementcomission             NUMERIC(18,4),
    topups                          NUMERIC(18,4),
    topupscomission                 NUMERIC(18,4),
    affilates                       NUMERIC(18,4),
    affilatescommission             NUMERIC(18,4),
    chargebacksrefunds              NUMERIC(18,4),
    chargebacksrefundscommission    NUMERIC(18,4),
    expenses                        NUMERIC(18,4),
    expensescommission              NUMERIC(18,4),
    notes222                        TEXT,
    notes333                        TEXT,
    notes444                        TEXT,
    path                            TEXT,
    ingection_id                    UUID,
    ingection_time                  TIMESTAMP,
    raw_hash                        CHAR(64),
    PRIMARY KEY (ingection_id)
);