"""Aifory transaction field mapping."""

AIFORY = {
    "wallet_bank": "Aifory",
    "columns": {
        "date": "время",
        "depositdate": "завершен",
        "withdrawaldate": "успешнооплачено",
        "pay_id": "clientorderid",
        "status": "Статус изменен",
        "amount": "сумма",
        "currency": "валюта",
        "commission": "комиссия",
        "commissioncurrency": ("no_data", "no_data"),
        "exchangerate": ("no_data", "no_data"),
        "finalamount": ("no_data", "no_data"),
        "project": ("project", "no_data"),
        "notes": ("organization", "no_data"),
        "reference": ("тип", "deposit"),
        "paymentmethod": ("no_data", "no_data"),
        "settlement": ("no_data", "no_data"),
        "settlementcomission": ("no_data", "no_data"),
        "topups": ("no_data", "no_data"),
        "topupscomission": ("no_data", "no_data"),
        "affilates": ("no_data", "no_data"),
        "affilatescommission": ("no_data", "no_data"),
        "chargebacksrefunds": ("no_data", "no_data"),
        "chargebacksrefundscommission": ("no_data", "no_data"),
        "expenses": ("no_data", "no_data"),
        "expensescommission": ("no_data", "no_data"),
        "notes222": ("no_data", "no_data"),
        "notes333": ("no_data", "no_data"),
        "notes444": ("no_data", "no_data"),
    },
}
