"""Biso transaction field mapping."""

BISO = {
    "wallet_bank": "Biso",
    "columns": {
        "date": "created",
        "depositdate": "created",
        "withdrawaldate": "created",
        "pay_id": "customerorderreference",
        "status": "status",
        "amount": "amount",
        "currency": "currency",
        "commission": ("fee_total", "no_data"),
        "commissioncurrency": ("no_data", "no_data"),
        "exchangerate": ("no_data", "no_data"),
        "finalamount": ("no_data", "no_data"),
        "project": "website",
        "notes": ("organization", "no_data"),
        "reference": "type",
        "paymentmethod": ("paymentmethod", "no_data"),
        "settlement": ("no_data", "no_data"),
        "settlementcomission": ("no_data", "no_data"),
        "topups": ("no_data", "no_data"),
        "topupscomission": ("no_data", "no_data"),
        "affilates": ("no_data", "no_data"),
        "affilatescommission": ("no_data", "no_data"),
        "chargebacksrefunds": ("no_data", "no_data"),
        "chargebacksrefundscommission": ("no_data", "no_data"),
        "expenses": ("no_data", "no_data"),
        "expensescommission": ("no_data", "no_data"),
        "notes222": ("no_data", "no_data"),
        "notes333": ("no_data", "no_data"),
        "notes444": ("no_data", "no_data"),
    },
}
