"""Jeton transaction field mapping."""

JETON = {
    "wallet_bank": "Jeton",
    "columns": {
        "date": "time",
        "depositdate": "time",
        "withdrawaldate": "time",
        "pay_id": "reference",
        "status": "status",
        "amount": "processingamount",
        "currency": "processingcurrency",
        "commission": ("fee_total", "no_data"),
        "commissioncurrency": ("no_data", "no_data"),
        "exchangerate": ("no_data", "no_data"),
        "finalamount": ("no_data", "no_data"),
        "project": "merchantname",
        "notes": ("organization", "no_data"),
        "reference": "category",
        "paymentmethod": ("no_data", "E-Wallet"),
        "settlement": ("no_data", "no_data"),
        "settlementcomission": ("no_data", "no_data"),
        "topups": ("no_data", "no_data"),
        "topupscomission": ("no_data", "no_data"),
        "affilates": ("no_data", "no_data"),
        "affilatescommission": ("no_data", "no_data"),
        "chargebacksrefunds": ("no_data", "no_data"),
        "chargebacksrefundscommission": ("no_data", "no_data"),
        "expenses": ("no_data", "no_data"),
        "expensescommission": ("no_data", "no_data"),
        "notes222": ("no_data", "no_data"),
        "notes333": ("no_data", "no_data"),
        "notes444": ("no_data", "no_data"),
    },
}
