"""Tunzer transaction field mapping."""

TUNZER = {
    "wallet_bank": "Tunzer",
    "columns": {
        "date": "ordercreatedsystemtimestamp",
        "depositdate": "orderchangedsystemtimestamp",
        "withdrawaldate": "ordercreatedsystemtimestamp",
        "pay_id": "ordermerchantid",
        "status": "transactionstatus",
        "amount": "transactionamount",
        "currency": "transactioncurrencycode",
        "commission": "transactioncommission",
        "commissioncurrency": ("no_data", "no_data"),
        "exchangerate": ("no_data", "no_data"),
        "finalamount": ("no_data", "no_data"),
        "project": "requestorname",
        "notes": ("transactiontype", "no_data"),
        "reference": "orderdescription",
        "paymentmethod": ("cardtype", "no_data"),
        "settlement": ("no_data", "no_data"),
        "settlementcomission": ("no_data", "no_data"),
        "topups": ("no_data", "no_data"),
        "topupscomission": ("no_data", "no_data"),
        "affilates": ("no_data", "no_data"),
        "affilatescommission": ("no_data", "no_data"),
        "chargebacksrefunds": ("no_data", "no_data"),
        "chargebacksrefundscommission": ("no_data", "no_data"),
        "expenses": ("no_data", "no_data"),
        "expensescommission": ("no_data", "no_data"),
        "notes222": ("no_data", "no_data"),
        "notes333": ("no_data", "no_data"),
        "notes444": ("no_data", "no_data"),
    },
}
